CREATE TABLE copy_trading_execution_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    copy_trading_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    leader_id BIGINT NOT NULL,
    leader_trade_id VARCHAR(100) NULL,
    market_id VARCHAR(100) NULL,
    side VARCHAR(10) NULL,
    outcome_index INT NULL,
    outcome VARCHAR(80) NULL,
    source VARCHAR(50) NULL,
    stage VARCHAR(40) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    leader_price DECIMAL(20, 8) NULL,
    leader_quantity DECIMAL(20, 8) NULL,
    leader_order_amount DECIMAL(20, 8) NULL,
    calculated_quantity DECIMAL(20, 8) NULL,
    order_price DECIMAL(20, 8) NULL,
    order_quantity DECIMAL(20, 8) NULL,
    order_id VARCHAR(120) NULL,
    aggregation_key VARCHAR(200) NULL,
    aggregation_trade_count INT NULL,
    message TEXT NOT NULL,
    detail_json TEXT NULL,
    created_at BIGINT NOT NULL,
    INDEX idx_copy_trading_execution_event_copy_trading_created_at (copy_trading_id, created_at),
    INDEX idx_copy_trading_execution_event_event_type (event_type),
    INDEX idx_copy_trading_execution_event_status (status)
);
