CREATE TABLE IF NOT EXISTS trader_candidate_pool (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    address VARCHAR(42) NOT NULL COMMENT 'Trader 地址',
    display_name VARCHAR(255) NULL COMMENT '展示名',
    profile_image VARCHAR(500) NULL COMMENT '头像',
    source VARCHAR(50) NOT NULL DEFAULT 'activity-ws' COMMENT '来源',
    recent_trade_count INT NOT NULL DEFAULT 0 COMMENT '累计成交笔数',
    recent_buy_count INT NOT NULL DEFAULT 0 COMMENT '累计买入笔数',
    recent_sell_count INT NOT NULL DEFAULT 0 COMMENT '累计卖出笔数',
    recent_volume DECIMAL(36, 8) NOT NULL DEFAULT 0 COMMENT '累计成交额',
    distinct_markets INT NOT NULL DEFAULT 0 COMMENT '去重市场数',
    tracked_market_ids_json TEXT NULL COMMENT '跟踪市场ID列表',
    last_market_id VARCHAR(100) NULL COMMENT '最近市场ID',
    last_market_title VARCHAR(500) NULL COMMENT '最近市场标题',
    last_market_slug VARCHAR(200) NULL COMMENT '最近市场slug',
    recommendation_score INT NULL COMMENT '最近推荐分',
    risk_score INT NULL COMMENT '最近风险分',
    low_risk BOOLEAN NOT NULL DEFAULT FALSE COMMENT '最近是否命中低风险',
    estimated_roi_rate DECIMAL(18, 6) NULL COMMENT '最近估算ROI比例',
    estimated_drawdown_rate DECIMAL(18, 6) NULL COMMENT '最近估算回撤比例',
    market_concentration_rate DECIMAL(18, 6) NULL COMMENT '最近市场集中度比例',
    active_days INT NULL COMMENT '最近评估活跃天数',
    current_position_count INT NULL COMMENT '最近评估持仓数',
    estimated_total_pnl DECIMAL(36, 8) NULL COMMENT '最近估算总盈亏',
    last_evaluated_at BIGINT NULL COMMENT '最近评估时间',
    first_seen_at BIGINT NOT NULL COMMENT '首次发现时间',
    last_seen_at BIGINT NOT NULL COMMENT '最近发现时间',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    updated_at BIGINT NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_trader_candidate_pool_address (address),
    KEY idx_trader_candidate_pool_last_seen (last_seen_at),
    KEY idx_trader_candidate_pool_low_risk (low_risk),
    KEY idx_trader_candidate_pool_recommendation (recommendation_score)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Trader 候选池快照';

CREATE TABLE IF NOT EXISTS trader_market_activity_pool (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    market_id VARCHAR(100) NOT NULL COMMENT '市场ID',
    trader_address VARCHAR(42) NOT NULL COMMENT 'Trader 地址',
    display_name VARCHAR(255) NULL COMMENT '展示名',
    trade_count INT NOT NULL DEFAULT 0 COMMENT '成交笔数',
    buy_count INT NOT NULL DEFAULT 0 COMMENT '买入笔数',
    sell_count INT NOT NULL DEFAULT 0 COMMENT '卖出笔数',
    total_volume DECIMAL(36, 8) NOT NULL DEFAULT 0 COMMENT '累计成交额',
    first_seen_at BIGINT NOT NULL COMMENT '首次发现时间',
    last_seen_at BIGINT NOT NULL COMMENT '最近发现时间',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    updated_at BIGINT NOT NULL COMMENT '更新时间',
    UNIQUE KEY uk_trader_market_activity_market_trader (market_id, trader_address),
    KEY idx_trader_market_activity_market (market_id),
    KEY idx_trader_market_activity_trader (trader_address),
    KEY idx_trader_market_activity_last_seen (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='市场-Trader 活跃快照';
