CREATE TABLE IF NOT EXISTS trader_activity_event_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_key VARCHAR(128) NOT NULL COMMENT '事件去重键',
    source VARCHAR(50) NOT NULL DEFAULT 'activity-ws' COMMENT '来源',
    trader_address VARCHAR(42) NOT NULL COMMENT 'Trader 地址',
    display_name VARCHAR(255) NULL COMMENT '展示名',
    market_id VARCHAR(100) NOT NULL COMMENT '市场ID',
    market_slug VARCHAR(200) NULL COMMENT '市场slug',
    asset VARCHAR(100) NULL COMMENT 'tokenId',
    transaction_hash VARCHAR(100) NULL COMMENT '交易哈希',
    side VARCHAR(16) NULL COMMENT 'BUY/SELL',
    outcome VARCHAR(50) NULL COMMENT '结果文本',
    outcome_index INT NULL COMMENT '结果索引',
    price DECIMAL(36, 18) NULL COMMENT '价格',
    size DECIMAL(36, 18) NULL COMMENT '数量',
    volume DECIMAL(36, 8) NULL COMMENT '成交额',
    event_timestamp BIGINT NOT NULL COMMENT '事件时间',
    received_at BIGINT NOT NULL COMMENT '接收时间',
    normalized_json TEXT NULL COMMENT '规范化事件JSON',
    raw_payload_json LONGTEXT NULL COMMENT '原始payload JSON',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    UNIQUE KEY uk_trader_activity_event_history_event_key (event_key),
    KEY idx_trader_activity_event_history_trader_time (trader_address, event_timestamp),
    KEY idx_trader_activity_event_history_market_time (market_id, event_timestamp),
    KEY idx_trader_activity_event_history_tx_hash (transaction_hash),
    KEY idx_trader_activity_event_history_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Trader activity 历史事件仓';
