CREATE TABLE manual_position_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    market_id VARCHAR(100) NOT NULL,
    market_title VARCHAR(500),
    market_slug VARCHAR(500),
    event_slug VARCHAR(500),
    market_icon VARCHAR(1000),
    side VARCHAR(100) NOT NULL,
    outcome_index INT NULL,
    closed_quantity DECIMAL(20, 8) NOT NULL,
    avg_price DECIMAL(20, 8) NOT NULL,
    close_price DECIMAL(20, 8) NOT NULL,
    initial_value DECIMAL(20, 8) NOT NULL,
    realized_pnl DECIMAL(20, 8) NOT NULL,
    percent_realized_pnl DECIMAL(20, 8) NULL,
    close_order_id VARCHAR(100) NOT NULL,
    close_order_status VARCHAR(50) NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    INDEX idx_manual_position_history_account_id (account_id),
    INDEX idx_manual_position_history_created_at (created_at),
    INDEX idx_manual_position_history_order_id (close_order_id)
);
