/**
 * 格式化数字，添加千分位分隔符，自动去除尾随零
 * @param value - 数字值（字符串或数字）
 * @param maxDecimals - 最大小数位数（默认不限制）
 * @returns 格式化后的字符串，如 "123,456.78"，如果值为空或无效则返回 ''
 * @example
 * formatNumber(1234567.89) => "1,234,567.89"
 * formatNumber(1234567.00) => "1,234,567"
 * formatNumber(1234.5678, 2) => "1,234.56"
 * formatNumber(100.00) => "100"
 * formatNumber(100.50) => "100.5"
 */
export const formatNumber = (value: string | number | undefined | null, maxDecimals?: number): string => {
  if (value === undefined || value === null || value === '') {
    return ''
  }

  const num = typeof value === 'string' ? parseFloat(value) : value
  if (isNaN(num)) {
    return ''
  }

  // 处理小数位数
  let numStr: string
  if (maxDecimals !== undefined) {
    const multiplier = Math.pow(10, maxDecimals)
    const truncated = Math.floor(num * multiplier) / multiplier
    numStr = truncated.toFixed(maxDecimals).replace(/\.?0+$/, '')
  } else {
    numStr = num.toString().replace(/\.?0+$/, '')
  }

  // 分离整数和小数部分
  const parts = numStr.split('.')
  const integerPart = parts[0]
  const decimalPart = parts[1]

  // 为整数部分添加千分位分隔符
  const formattedInteger = integerPart.replace(/\B(?=(\d{3})+(?!\d))/g, ',')

  // 组合结果
  return decimalPart ? `${formattedInteger}.${decimalPart}` : formattedInteger
}

/**
 * 格式化 USDC 金额，带千分位分隔符
 * 最多显示 4 位小数，自动去除尾随零（截断，不四舍五入）
 * @param value - 金额值（字符串或数字）
 * @returns 格式化后的字符串，如 "1,234.56"，如果值为空或无效则返回 '-'
 * @example
 * formatUSDC(1234.56) => "1,234.56"
 * formatUSDC(1234567.8901) => "1,234,567.8901"
 * formatUSDC(1234.00) => "1,234"
 * formatUSDC(1.23) => "1.23"
 * formatUSDC(1) => "1"
 */
export const formatUSDC = (value: string | number | undefined | null): string => {
  if (value === undefined || value === null || value === '') {
    return '-'
  }

  const num = typeof value === 'string' ? parseFloat(value) : value
  if (isNaN(num)) {
    return '-'
  }

  return formatNumber(num, 4)
}

// 统一导出 ethers 相关工具函数
export {
  getAddressFromPrivateKey,
  getAddressFromMnemonic,
  getPrivateKeyFromMnemonic,
  isValidMnemonic,
  isValidWalletAddress,
  isValidPrivateKey
} from './ethers'

// 统一导出 auth 相关工具函数
export {
  getToken,
  setToken,
  removeToken,
  hasToken
} from './auth'

// 统一导出 version 相关工具函数
export {
  getVersionInfo,
  getVersionText,
  getGitHubTagUrl
} from './version'

/**
 * 检查订单ID是否为自动生成的
 * 自动生成的订单ID通常以 "AUTO_" 或 "AUTO_FIFO_" 开头
 * @param orderId - 订单ID
 * @returns 如果是自动生成的订单ID，返回 true，否则返回 false
 */
export const isAutoGeneratedOrderId = (orderId: string | undefined | null): boolean => {
  if (!orderId) return false
  return orderId.startsWith('AUTO_') || orderId.startsWith('AUTO_FIFO_')
}

/**
 * 构建 Polymarket 市场 URL
 * 对于 moneyline 市场，跳转到 moneyline 页面
 * 注意：目前无法自动判断市场是否为 moneyline,需要后端提供标识
 * @param marketSlug - 市场 slug（用于显示）
 * @param eventSlug - 跳转用的 slug（从 events[0].slug 获取，优先使用）
 * @param marketCategory - 市场分类（sports, crypto 等）
 * @param marketId - 市场ID（作为后备）
 * @param isMoneyline - 是否为 moneyline 市场（需要后端提供）
 * @returns Polymarket URL，如果无法构建则返回 null
 */
export const getPolymarketUrl = (
  marketSlug?: string | null,
  eventSlug?: string | null,  // 跳转用的 slug（优先使用）
  _marketCategory?: string | null,  // 保留参数以便未来使用
  marketId?: string | null,
  isMoneyline?: boolean
): string | null => {
  // 优先使用 eventSlug（跳转用的 slug）
  const slug = eventSlug || marketSlug

  if (slug) {
    // 如果是 moneyline 市场，跳转到 moneyline 页面
    if (isMoneyline === true) {
      return `https://polymarket.com/event/${slug}/moneyline`
    }
    // 其他市场跳转到普通市场页面
    return `https://polymarket.com/event/${slug}`
  }

  // 如果没有 slug，使用 marketId（作为后备）
  if (marketId && marketId.startsWith('0x')) {
    return `https://polymarket.com/condition/${marketId}`
  }

  return null
}

/**
 * 复制文本到剪贴板
 * @param text - 要复制的文本
 * @returns Promise<boolean> - 复制成功返回 true，失败返回 false
 */
export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text)
      return true
    } else {
      // 降级方案：使用传统的 document.execCommand
      const textArea = document.createElement('textarea')
      textArea.value = text
      textArea.style.position = 'fixed'
      textArea.style.left = '-999999px'
      textArea.style.top = '-999999px'
      document.body.appendChild(textArea)
      textArea.focus()
      textArea.select()
      const successful = document.execCommand('copy')
      document.body.removeChild(textArea)
      return successful
    }
  } catch (error) {
    console.error('复制到剪贴板失败:', error)
    return false
  }
}

export const formatMultiplierSummary = (mode?: string, tradeMultiplier?: string | null, tieredMultipliers?: MultiplierTier[] | null): string => {
  if (!mode || mode === 'NONE') {
    return '无'
  }

  if (mode === 'SINGLE') {
    return tradeMultiplier ? `${formatNumber(tradeMultiplier, 4)}x` : '未设置'
  }

  if (mode === 'TIERED') {
    if (!tieredMultipliers || tieredMultipliers.length === 0) {
      return '未设置'
    }
    return tieredMultipliers
      .map((tier) => `${tier.min}-${tier.max ?? '∞'}:${tier.multiplier}x`)
      .join(', ')
  }

  return mode
}

export const formatCopyModeSummary = (config: {
  copyMode?: string
  copyRatio?: string | null
  fixedAmount?: string | null
  adaptiveMinRatio?: string | null
  adaptiveMaxRatio?: string | null
  adaptiveThreshold?: string | null
}): string => {
  if (config.copyMode === 'FIXED') {
    return `固定 ${formatUSDC(config.fixedAmount)} USDC`
  }

  if (config.copyMode === 'ADAPTIVE') {
    return `自适应 ${formatNumber(config.copyRatio || '0', 4)}x (${formatNumber(config.adaptiveMinRatio || '0', 4)}x-${formatNumber(config.adaptiveMaxRatio || '0', 4)}x / ${formatUSDC(config.adaptiveThreshold)} USDC)`
  }

  return `比例 ${formatNumber(config.copyRatio || '0', 4)}x`
}

type RepeatAddReductionConfig = {
  repeatAddReductionEnabled?: boolean | null
  repeatAddReductionStrategy?: string | null
  repeatAddReductionValueType?: string | null
  repeatAddReductionPercent?: string | number | null
  repeatAddReductionFixedAmount?: string | number | null
}

const toOptionalNumber = (value: string | number | null | undefined): number | null => {
  if (value === undefined || value === null || value === '') {
    return null
  }
  const parsed = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(parsed) ? parsed : null
}

export const validateRepeatAddReductionConfig = (config: RepeatAddReductionConfig): string | null => {
  if (!config.repeatAddReductionEnabled) {
    return null
  }

  if (config.repeatAddReductionStrategy !== 'UNIFORM' && config.repeatAddReductionStrategy !== 'PROGRESSIVE') {
    return '请选择重复加仓缩量策略'
  }

  if (config.repeatAddReductionValueType !== 'PERCENT' && config.repeatAddReductionValueType !== 'FIXED') {
    return '请选择重复加仓缩量类型'
  }

  if (config.repeatAddReductionValueType === 'PERCENT') {
    const percent = toOptionalNumber(config.repeatAddReductionPercent)
    if (percent === null || percent <= 0 || percent >= 100) {
      return '重复加仓缩量百分比必须大于 0 且小于 100'
    }
  }

  if (config.repeatAddReductionValueType === 'FIXED') {
    const fixedAmount = toOptionalNumber(config.repeatAddReductionFixedAmount)
    if (fixedAmount === null || fixedAmount <= 0) {
      return '重复加仓固定减额必须大于 0'
    }
  }

  return null
}

export const buildRepeatAddReductionPayload = (config: RepeatAddReductionConfig): {
  repeatAddReductionEnabled: boolean
  repeatAddReductionStrategy?: 'UNIFORM' | 'PROGRESSIVE'
  repeatAddReductionValueType?: 'PERCENT' | 'FIXED'
  repeatAddReductionPercent?: string
  repeatAddReductionFixedAmount?: string
} => {
  const enabled = Boolean(config.repeatAddReductionEnabled)
  const strategy = config.repeatAddReductionStrategy === 'PROGRESSIVE' ? 'PROGRESSIVE' : 'UNIFORM'
  const valueType = config.repeatAddReductionValueType === 'FIXED' ? 'FIXED' : 'PERCENT'

  return {
    repeatAddReductionEnabled: enabled,
    repeatAddReductionStrategy: enabled ? strategy : undefined,
    repeatAddReductionValueType: enabled ? valueType : undefined,
    repeatAddReductionPercent: enabled && valueType === 'PERCENT' && config.repeatAddReductionPercent !== undefined && config.repeatAddReductionPercent !== null && config.repeatAddReductionPercent !== ''
      ? String(config.repeatAddReductionPercent)
      : undefined,
    repeatAddReductionFixedAmount: enabled && valueType === 'FIXED' && config.repeatAddReductionFixedAmount !== undefined && config.repeatAddReductionFixedAmount !== null && config.repeatAddReductionFixedAmount !== ''
      ? String(config.repeatAddReductionFixedAmount)
      : undefined
  }
}

export const formatRepeatAddReductionSummary = (config: RepeatAddReductionConfig): string => {
  if (!config.repeatAddReductionEnabled) {
    return ''
  }

  const strategy = config.repeatAddReductionStrategy || 'UNIFORM'
  const valueType = config.repeatAddReductionValueType || 'PERCENT'

  if (valueType === 'FIXED') {
    const fixedAmount = formatUSDC(config.repeatAddReductionFixedAmount)
    return strategy === 'PROGRESSIVE'
      ? `重复加仓：每次比首笔少 ${fixedAmount} USDC`
      : `重复加仓：后续固定 ${fixedAmount} USDC`
  }

  const percent = formatNumber(config.repeatAddReductionPercent ?? '', 4)
  return strategy === 'PROGRESSIVE'
    ? `重复加仓：第 n 笔=首笔×${percent}%^(n-1)`
    : `重复加仓：后续固定为首笔 ${percent}%`
}

type MarketFilterSummaryConfig = {
  marketCategoryMode?: string | null
  marketCategories?: Array<string | null | undefined> | null
  marketIntervalMode?: string | null
  marketIntervals?: Array<string | number | null | undefined> | null
  marketSeriesMode?: string | null
  marketSeries?: Array<string | null | undefined> | null
  maxMarketEndDate?: number | null
}

const compactSummaryValues = (values: string[], maxItems = 2): string => {
  if (values.length <= maxItems) {
    return values.join(', ')
  }

  return `${values.slice(0, maxItems).join(', ')} +${values.length - maxItems}`
}

export const formatMarketIntervalLabel = (seconds: string | number | null | undefined): string => {
  const numericSeconds = typeof seconds === 'string' ? Number(seconds) : seconds
  if (!numericSeconds || !Number.isFinite(numericSeconds)) {
    return ''
  }

  if (numericSeconds % 86400 === 0) {
    return `${numericSeconds / 86400}d`
  }
  if (numericSeconds % 3600 === 0) {
    return `${numericSeconds / 3600}h`
  }
  if (numericSeconds % 60 === 0) {
    return `${numericSeconds / 60}m`
  }
  return `${numericSeconds}s`
}

export const formatDurationLabel = (durationMs: number | null | undefined): string => {
  if (!durationMs || !Number.isFinite(durationMs) || durationMs <= 0) {
    return ''
  }

  const totalSeconds = Math.floor(durationMs / 1000)
  if (totalSeconds % 86400 === 0) {
    return `${totalSeconds / 86400}d`
  }
  if (totalSeconds % 3600 === 0) {
    return `${totalSeconds / 3600}h`
  }
  if (totalSeconds % 60 === 0) {
    return `${totalSeconds / 60}m`
  }
  return `${totalSeconds}s`
}

export const formatMarketFilterSummary = (config: MarketFilterSummaryConfig): string[] => {
  const summary: string[] = []

  const categoryValues = Array.from(
    new Set((config.marketCategories || []).map((value) => String(value || '').trim()).filter(Boolean))
  )
  if (config.marketCategoryMode === 'WHITELIST' && categoryValues.length > 0) {
    summary.push(`分类: ${compactSummaryValues(categoryValues)}`)
  } else if (config.marketCategoryMode === 'BLACKLIST' && categoryValues.length > 0) {
    summary.push(`分类排除: ${compactSummaryValues(categoryValues)}`)
  }

  const intervalValues = Array.from(
    new Set(
      (config.marketIntervals || [])
        .map((value) => formatMarketIntervalLabel(value))
        .filter(Boolean)
    )
  )
  if (config.marketIntervalMode === 'WHITELIST' && intervalValues.length > 0) {
    summary.push(`周期: ${compactSummaryValues(intervalValues)}`)
  } else if (config.marketIntervalMode === 'BLACKLIST' && intervalValues.length > 0) {
    summary.push(`周期排除: ${compactSummaryValues(intervalValues)}`)
  }

  const seriesValues = Array.from(
    new Set((config.marketSeries || []).map((value) => String(value || '').trim()).filter(Boolean))
  )
  if (config.marketSeriesMode === 'WHITELIST' && seriesValues.length > 0) {
    summary.push(`系列: ${compactSummaryValues(seriesValues)}`)
  } else if (config.marketSeriesMode === 'BLACKLIST' && seriesValues.length > 0) {
    summary.push(`系列排除: ${compactSummaryValues(seriesValues)}`)
  }

  const durationLabel = formatDurationLabel(config.maxMarketEndDate)
  if (durationLabel) {
    summary.push(`剩余<=${durationLabel}`)
  }

  return summary
}

type MultiplierTierInput = {
  min?: string | number | null
  max?: string | number | null
  multiplier?: string | number | null
}

type NormalizedMultiplierTier = {
  min: string
  max: string | null
  multiplier: string
}

type MultiplierTierValidationResult = {
  isValid: boolean
  message?: string
  tiers: NormalizedMultiplierTier[]
}

const parseTierValue = (value: string | number | null | undefined): number | null => {
  if (value === undefined || value === null || value === '') {
    return null
  }
  const parsed = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(parsed) ? parsed : null
}

export const validateAndNormalizeMultiplierTiers = (
  tiers?: MultiplierTierInput[] | null
): MultiplierTierValidationResult => {
  if (!tiers || tiers.length === 0) {
    return {
      isValid: false,
      message: '请至少配置一档分层 multiplier',
      tiers: []
    }
  }

  try {
    const normalized = tiers.map((tier, index) => {
      const min = parseTierValue(tier.min)
      const max = parseTierValue(tier.max)
      const multiplier = parseTierValue(tier.multiplier)

      if (min === null) {
        throw new Error(`第 ${index + 1} 档的最小金额不能为空`)
      }
      if (multiplier === null) {
        throw new Error(`第 ${index + 1} 档的 multiplier 不能为空`)
      }
      if (min < 0) {
        throw new Error(`第 ${index + 1} 档的最小金额不能小于 0`)
      }
      if (multiplier < 0) {
        throw new Error(`第 ${index + 1} 档的 multiplier 不能小于 0`)
      }
      if (max !== null && max <= min) {
        throw new Error(`第 ${index + 1} 档的最大金额必须大于最小金额`)
      }

      return {
        min,
        max,
        multiplier
      }
    }).sort((a, b) => a.min - b.min)

    normalized.forEach((tier, index) => {
      if (tier.max === null && index !== normalized.length - 1) {
        throw new Error('无上界档位只能放在最后一档')
      }
      if (index < normalized.length - 1) {
        const next = normalized[index + 1]
        if (tier.max !== null && tier.max > next.min) {
          throw new Error('分层区间不能重叠')
        }
      }
    })

    return {
      isValid: true,
      tiers: normalized.map((tier) => ({
        min: tier.min.toString(),
        max: tier.max === null ? null : tier.max.toString(),
        multiplier: tier.multiplier.toString()
      }))
    }
  } catch (error) {
    return {
      isValid: false,
      message: error instanceof Error ? error.message : '分层 multiplier 配置无效',
      tiers: []
    }
  }
}

import type { MultiplierTier } from '../types'
